@host = http://127.0.0.1:8000/api

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiM2NjM2M0OTQyNGVmMGIzYmMxMWI0YjM2ZTBjZTY3NTFiMjExYjJkYTVkMWVhODJjYzQwYTViNDRhYzk5NzYxN2Q5MGRhZjZiODJlNTkxMzUiLCJpYXQiOjE2ODk1ODk5OTAuNjQ4NjE0LCJuYmYiOjE2ODk1ODk5OTAuNjQ4NjE4LCJleHAiOjE3MjEyMTIzOTAuNjMyMDYsInN1YiI6IjYzIiwic2NvcGVzIjpbXX0.JZ8q5jhAsyKuDY6V2Zvz8cJlz4CzwTLFzOZBb3mno8TojT4FYUhjwJp1bXJZMntkFilpnIVZCRXNi7xKswi-iubIOdZHLgFl2L4Rx4_vXJKNENlN1CdvKzVxBqf5P6Bq5ieh2WrGL6nGyVcNLasqiAQ4sur4FXx3ZOfJr7rqci4KXz8opC_BiTduTqfZagaRqv0_L8BZh-G2qreNd2jU_2XW_KM0KDxarYvcPgxWbCdbisiJNklqrNCHn6-AcJYWWHDGgRggijan2d-4ZsjmZYyOrGfb7CbaHGJOMDJAo50sOxbDbzUFVsxGQ-SVskbC3s0kGciW4iyUZGLdP0fvSAylrwiR0VGAxY1VcdaWz8TYS2GAOyz66bazdYdRsC2MCrdjrHANW-ec3m8xg0C9SpudoGegvXLPsHtYfFwQX0PIVEOctLWa7CGhJ-ABEWLEW4g0PxZlYY6XwuXJmZx5-e8Qhwp7glKOCHFt1QvN99R3s-0kuSkAv5e818nb1NrT0EDnv73A1wYgyHyB4ZD0H1ts3qhbn1_reovkCwpOKVNtJCfVqT8RnTTWAYPZY7wxFryBJJU1P5KE3pfDHOJ6yVYuz82F7_Bs2bTRRCRVqV7XXI-jQwiljZpLhQc83HAJpyV1zwIuwDMHtljTtCJIUd9thRLEg5LN31putap-g0I
##get user
GET {{host}}/auth/user HTTP/1.1
Content-Type: application/json

{

}

################
## login user
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "karima@gmail.com",
  "password": "123456"

}


################
## Register user
POST {{host}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "karima",
  "email": "asseasd66@gmail.com",
  "password": "222222"
}


################
## Otp verify
POST {{host}}/auth/verify-otp HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "otp": "995866"
}


################
## Otp Re-verify
POST {{host}}/auth/resendOtp HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{


}


################
## Forget password
POST {{host}}/auth/forget-password HTTP/1.1
Content-Type: application/json

{
 "email": "karima987@gmail.com"
}

################
## verift-Forget password
POST {{host}}/auth/verify-forget-password HTTP/1.1
Content-Type: application/json

{
 "otp": "6627302",
 "email": "karima987@gmail.com"
}
