@host = http://127.0.0.1:8000/api

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODkzYTY4MTRhNjg0OTRkZWU1ZDFlN2YzYmMwMmNlMzkyYzM1NDk0NDYyOWMzY2I1M2VlZGY1MmMwMWFkNTVhZDA1ZWFlZjg2ZDI1ODBjZjEiLCJpYXQiOjE2ODk2NTcwODYuMzM2NDA3LCJuYmYiOjE2ODk2NTcwODYuMzM2NDExLCJleHAiOjE3MjEyNzk0ODYuMzI2NTU1LCJzdWIiOiI1Iiwic2NvcGVzIjpbXX0.cmuGnQE9TPAM0Yf48MDdfH7ioW4Rc_e32MHkn7LQutgAaWTzvn48eKnPLPRSYenxebABIeFuBuqCkDkNVnU4aayUP64KlrMArn51OgDMeVkpyPRARbTSyZAzzdXEfqYlFRmK1PAI1wnNAeo0Odg3y29mFKMnTnOrU7FgOuFEDEEhdFLQ98AGuKvQ3iVB9JyXWG_5Jl37RaYXSYEOrw0MSVw_dP6r_86_KYJVjf2MnJAg6mg8CA-IZeV-UdnfSSI_J-Jix3DK7CeDD3e3MHQRxCqLall_kIxizXl43Fs73lumsEgsQP45EwEV6DIEErlgqjTM5rlv1z4S7bZbth36FOu2Y6topNHk-qq3sxAr4_QKaoHjLqLpktE4GhSUu43Wh9Z3XPKYSwiup7J0H-OwVFoO0DuiCjLBfgREhAi9-cqghXGklDet_AiOC7t0osjM4JqFKRH8H_Wn6D-aRZNjzrPEczKPNibHNRWhCAvaSWQjezwT10NxTWNLiMVZKGYmCLZfpt4I3ykNMqnyBgQZhRPitKuSc4OAOE0VlaUgSn45CMJvhFOeZAt0_4Kse7dM_yxkJ59t4p36SDq5MJLFxdi4eXXLMlTUkX-VTXk05H-7DDiMKaVFNGWk-jeunIHq4MQD6vFt3CcFZcVpTGleZe1k6vRq_vJBbzBBrZeEEFQ
##get user
GET {{host}}/auth/user HTTP/1.1
Content-Type: application/json

{

}

################
## login user
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "karima@gmail.com",
  "password": "123456q"

}


################
## Register user
POST {{host}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "karima",
  "email": "karimaa@gmail.com",
  "password": "123456"
}


################
## Otp verify
POST {{host}}/auth/verify-otp HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "otp": "249878"
}


################
## Otp Re-verify
POST {{host}}/auth/resendOtp HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{


}


################
## Forget password
POST {{host}}/auth/forget-password HTTP/1.1
Content-Type: application/json

{
 "email": "karima@gmail.com"
}

################
## verify-Forget password
POST {{host}}/auth/verify-forget-password HTTP/1.1
Content-Type: application/json

{
 "otp": "8443579",
 "email": "karima@gmail.com"
}

################
## Reset-Forget password
POST {{host}}/auth/reset-password HTTP/1.1
Content-Type: application/json

{
    "email": "karimaa@gmail.com",
    "password": "123456q",
    "password_confirmation": "123456q"
}
